### ISSUE TITLE
createFareMultiplier() multiplier desc incorrect

### ISSUE THREAD

**Issue by alenjo874** [learn-co-curriculum/phase-1-first-class-functions-lab#10]
### Canvas Link

https://learning.flatironschool.com/courses/4985/assignments/163544?module_item_id=351901

### Concern

For this test, createFareMultiplier(), the multiplier on canvas shows 4, but on the test it is 5.

**Comment by AlveeM** [comment]
Hello, and thanks for submitting the issue and providing feedback.

The `createFareMultiplier` function is expected to be a general function. The prompt referencing `4` as an input in the Canvas lesson is an example of what the output for a given input would be.

The tests will usually check your function using different inputs than the ones mentioned in the lesson since the students are likely to check those on their own.

I will update the lesson to make the intention clear. Note, however, that if you are working in Canvas the changes may not show up there, but they will for future students.

Thanks again for bringing up the issue and helping us refine the curriculum! Happy coding! 💙
